### PR TITLE
[WIP] GUI-Manager and User-Modifier-Interface

### PR DESCRIPTION
**Pull request by Flo56958**
TODO:
- [ ]  #48
- [x] /mt mods GUI
- [ ] Functionality of Buttons (switch page, use command, etc.)

### CODE REVIEW

**Comment by Draycia** [comment]
image

We should probably put descriptions on their own line.

Bonus points if we auto wrap the description so that lengthy ones don't force the tooltip off of the screen.

**Comment by Draycia** [comment]
Seems modifier descriptions contain both bits of text.
Some way of splitting them, either in the Modifier class or in GUIs, would be good.

**Comment by Draycia** [comment]
Also how about this for a format instead?
image

**Comment by Flo56958** [comment]
> Also how about this for a format instead?
> image
> 
> I can commit my changes to the PR if you want.

Would be nice :)

**Comment by Draycia** [comment]
Infinity and Melting have descriptions that need to be auto split to reduce tooltip width.

**Pull request merged**
