### PR TITLE
Slight Modifier changes and /mt mods enhancements

### PR DESCRIPTION
**Pull request by Draycia**

### CODE REVIEW

**Comment by Draycia** [comment]
I don't speak any of the supported languages except English, so I cannot provide accurate translations for the new language entry.

I used google translate for all but Chinese, as the quality of the translation that google provided for it was too low.

**Comment by Flo56958** [comment]
I dont know if ToolType.name is really a good solution as it could also be translated, instead of using the names in the code

**Comment by Draycia** [comment]
I plan on doing that before this is merged.

**Comment by Draycia** [comment]
TODO:

- [ ] Fix enchant costs (accidentally overwrote existing ones)
- [ ] Make sure all mods have a max level (accidentally removed a few)

**Comment by Draycia** [comment]
Tested and seems to work. Merge if you think it's good.

**Pull request merged**
